name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "core-v*.*.*"
      - "derive-v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}
      - name: Run tests
        run: cargo test --verbose --workspace --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}
      - name: Run clippy
        run: cargo clippy --workspace --all-features -- -D warnings

  publish-nami-core:
    name: Publish nami-core
    needs: [test, clippy]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/core-v')
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}
      - name: Publish nami-core
        run: cargo publish -p nami-core --token ${{ secrets.CARGO_API_TOKEN }}

  publish-nami-derive:
    name: Publish nami-derive
    needs: [test, clippy]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/derive-v')
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}
      - name: Publish nami-derive
        run: cargo publish -p nami-derive --token ${{ secrets.CARGO_API_TOKEN }}

  publish-nami:
    name: Publish nami
    needs: [test, clippy]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}
      - name: Publish nami
        run: cargo publish -p nami --token ${{ secrets.CARGO_API_TOKEN }}
